[manifest]
version = "1.0.0"
dump_lua = true
priority = 11


[[patches]]
[patches.module]
source = "internal/init.lua"
before = "main.lua"
name = "your-mod-name.init"

[[patches]]
[patches.module]
source = "libs/nativefs.lua"
before = "main.lua"
name = "your-mod-name.nfs"

# Add core functionality
[[patches]]
[patches.copy]
target = "main.lua"
position = "append"
sources = [
    "your-mod-name.lua",
]
